name: camera_bloc
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  permission_handler: ^10.4.3
  syncfusion_flutter_gauges: ^20.4.51
  video_player: ^2.7.0
  visibility_detector: ^0.4.0+2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  bloc_test: ^9.1.4
  mockito:

flutter:

  uses-material-design: true
